PACKAGE_NAME="rtl8812au-mesh"
PACKAGE_VERSION="0.1.5"
MAKE[0]="make KVER=${kernelver} all"
CLEAN="make KVER=${kernelver} clean"
AUTOINSTALL="yes"

BUILT_MODULE_NAME[0]="rtw_core"
BUILT_MODULE_NAME[1]="rtw_usb"
BUILT_MODULE_NAME[2]="rtw_88xxa"
BUILT_MODULE_NAME[3]="rtw_8812a"
BUILT_MODULE_NAME[4]="rtw_8812au"

for index in 0 1 2 3 4; do
	BUILT_MODULE_LOCATION[$index]="."
	DEST_MODULE_LOCATION[$index]="/updates/dkms"
done
