PACKAGE_NAME="rtl8812au-mesh"
PACKAGE_VERSION="0.1.6"
MAKE[0]="make KVER=${kernelver} all"
CLEAN="make KVER=${kernelver} clean"
AUTOINSTALL="yes"

BUILT_MODULE_NAME[0]="rtw_core"
BUILT_MODULE_NAME[1]="rtw_usb"
BUILT_MODULE_NAME[2]="rtw_88xxa"
BUILT_MODULE_NAME[3]="rtw_8812a"
BUILT_MODULE_NAME[4]="rtw_8812au"

BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/updates/dkms"
BUILT_MODULE_LOCATION[1]="."
DEST_MODULE_LOCATION[1]="/updates/dkms"
BUILT_MODULE_LOCATION[2]="."
DEST_MODULE_LOCATION[2]="/updates/dkms"
BUILT_MODULE_LOCATION[3]="."
DEST_MODULE_LOCATION[3]="/updates/dkms"
BUILT_MODULE_LOCATION[4]="."
DEST_MODULE_LOCATION[4]="/updates/dkms"
